timezone: "Melbourne"
name: "Website name"
url: ""
app_domain: ""
cdn_url: ""
breakpoints:
  -
    name: "phone"
    query: "(max-width: 480px)"
authors:
  solnic:
    name: Piotr Solnica
    url: https://twitter.com/_solnic_
  timriley:
    name: Tim Riley
    url: https://twitter.com/timriley
  flash-gordon:
    name: Nikita Shilnikov
    url: https://twitter.com/NikitaShilnikov
gems:
  -
    name: dry-validation
    desc: Powerful data validation based on predicate logic
  -
    name: dry-types
    desc: Flexible type system with many built-in types
  -
    name: dry-struct
    desc: Attribute DSL for struct-like objects
  -
    name: dry-transaction
    desc: Business transaction DSL
  -
    name: dry-container
    desc: Simple and thread-safe IoC container
  -
    name: dry-auto_inject
    desc: Container-agnostic constructor injection mixin
  -
    name: dry-equalizer
    desc: Simple mixin providing equality methods
  -
    name: dry-inflector
    desc: Standalone inflections
  -
    name: dry-system
    desc: Organize your code into reusable components
  -
    name: dry-configurable
    desc: Thread-safe configuration mixin
  -
    name: dry-initializer
    desc: DSL for defining initializer params and options
  -
    name: dry-logic
    desc: Predicate logic with composable rules
  -
    name: dry-matcher
    desc: Flexible, expressive pattern matching
  -
    name: dry-monads
    desc: Useful, common monads in idiomatic Ruby
  -
    name: dry-view
    desc: Functional, standalone view rendering
  -
    name: dry-core
    desc: A toolset of small support modules used throughout the dry-rb & rom-rb ecosystems
  -
    name: dry-web-roda
    desc: A simple web stack combining Roda with the dry-rb and rom-rb gems
  -
    name: dry-events
    desc: Standalone pub/sub API
