timezone: "Melbourne"
name: "Website name"
url: ""
app_domain: ""
cdn_url: ""
breakpoints:
  -
    name: "phone"
    query: "(max-width: 480px)"
authors:
  solnic:
    name: Piotr Solnica
    url: https://twitter.com/_solnic_
gems:
  -
    name: dry-validation
    desc: Powerful data validation based on predicate logic
  -
    name: dry-types
    desc: Flexible type system with many built-in types
  -
    name: dry-transaction
    desc: Business transaction DSL
  -
    name: dry-container
    desc: Simple and thread-safe IoC container
  -
    name: dry-auto_inject
    desc: Container-agnostic constructor injection mixin
  -
    name: dry-equalizer
    desc: Simple mixing providing equality methods
  -
    name: dry-component
    desc: Organize your code into reusable components
  -
    name: dry-configurable
    desc: Thread-safe configuration mixin
  -
    name: dry-logic
    desc: Predicate logic with composable rules
